require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalaryActivitiesController do

  # This should return the minimal set of attributes required to create a valid
  # SalaryActivity. As you add validations to SalaryActivity, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "previous_salary" => "1.5" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalaryActivitiesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all salary_activities as @salary_activities" do
      salary_activity = SalaryActivity.create! valid_attributes
      get :index, {}, valid_session
      assigns(:salary_activities).should eq([salary_activity])
    end
  end

  describe "GET show" do
    it "assigns the requested salary_activity as @salary_activity" do
      salary_activity = SalaryActivity.create! valid_attributes
      get :show, {:id => salary_activity.to_param}, valid_session
      assigns(:salary_activity).should eq(salary_activity)
    end
  end

  describe "GET new" do
    it "assigns a new salary_activity as @salary_activity" do
      get :new, {}, valid_session
      assigns(:salary_activity).should be_a_new(SalaryActivity)
    end
  end

  describe "GET edit" do
    it "assigns the requested salary_activity as @salary_activity" do
      salary_activity = SalaryActivity.create! valid_attributes
      get :edit, {:id => salary_activity.to_param}, valid_session
      assigns(:salary_activity).should eq(salary_activity)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SalaryActivity" do
        expect {
          post :create, {:salary_activity => valid_attributes}, valid_session
        }.to change(SalaryActivity, :count).by(1)
      end

      it "assigns a newly created salary_activity as @salary_activity" do
        post :create, {:salary_activity => valid_attributes}, valid_session
        assigns(:salary_activity).should be_a(SalaryActivity)
        assigns(:salary_activity).should be_persisted
      end

      it "redirects to the created salary_activity" do
        post :create, {:salary_activity => valid_attributes}, valid_session
        response.should redirect_to(SalaryActivity.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved salary_activity as @salary_activity" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalaryActivity.any_instance.stub(:save).and_return(false)
        post :create, {:salary_activity => { "previous_salary" => "invalid value" }}, valid_session
        assigns(:salary_activity).should be_a_new(SalaryActivity)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalaryActivity.any_instance.stub(:save).and_return(false)
        post :create, {:salary_activity => { "previous_salary" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested salary_activity" do
        salary_activity = SalaryActivity.create! valid_attributes
        # Assuming there are no other salary_activities in the database, this
        # specifies that the SalaryActivity created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SalaryActivity.any_instance.should_receive(:update_attributes).with({ "previous_salary" => "1.5" })
        put :update, {:id => salary_activity.to_param, :salary_activity => { "previous_salary" => "1.5" }}, valid_session
      end

      it "assigns the requested salary_activity as @salary_activity" do
        salary_activity = SalaryActivity.create! valid_attributes
        put :update, {:id => salary_activity.to_param, :salary_activity => valid_attributes}, valid_session
        assigns(:salary_activity).should eq(salary_activity)
      end

      it "redirects to the salary_activity" do
        salary_activity = SalaryActivity.create! valid_attributes
        put :update, {:id => salary_activity.to_param, :salary_activity => valid_attributes}, valid_session
        response.should redirect_to(salary_activity)
      end
    end

    describe "with invalid params" do
      it "assigns the salary_activity as @salary_activity" do
        salary_activity = SalaryActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalaryActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => salary_activity.to_param, :salary_activity => { "previous_salary" => "invalid value" }}, valid_session
        assigns(:salary_activity).should eq(salary_activity)
      end

      it "re-renders the 'edit' template" do
        salary_activity = SalaryActivity.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalaryActivity.any_instance.stub(:save).and_return(false)
        put :update, {:id => salary_activity.to_param, :salary_activity => { "previous_salary" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested salary_activity" do
      salary_activity = SalaryActivity.create! valid_attributes
      expect {
        delete :destroy, {:id => salary_activity.to_param}, valid_session
      }.to change(SalaryActivity, :count).by(-1)
    end

    it "redirects to the salary_activities list" do
      salary_activity = SalaryActivity.create! valid_attributes
      delete :destroy, {:id => salary_activity.to_param}, valid_session
      response.should redirect_to(salary_activities_url)
    end
  end

end
